import type { PhotoPageTemplateDefinition } from "./types"

/**
 * V1 photo template library — fixed print geometry (% of page).
 * Polaroid padding / caption sit inside each slot; template only places frames.
 */
export const PHOTO_PAGE_TEMPLATES: PhotoPageTemplateDefinition[] = [
  // --- 2 photos ---
  {
    id: "PHOTO_2_A",
    label: "Deux photos côte à côte",
    pageType: "COLLAGE",
    photoCount: 2,
    pageTitleSlot: { x: 8, y: 3, width: 84, height: 5 },
    supportedOrientationPatterns: [
      { portraits: 2, weight: 12 },
      { portraits: 1, squares: 1, weight: 8 },
      { squares: 2, weight: 7 },
    ],
    slots: [
      {
        id: "slot1",
        role: "secondary",
        x: 4,
        y: 10,
        width: 44,
        height: 82,
        rotationDeg: -1.1,
        imageFit: "cover",
        preferredOrientations: ["PORTRAIT", "SQUARE"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "slot2",
        role: "secondary",
        x: 52,
        y: 10,
        width: 44,
        height: 82,
        rotationDeg: 1.0,
        imageFit: "cover",
        preferredOrientations: ["PORTRAIT", "SQUARE"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },
  {
    id: "PHOTO_2_B",
    label: "Deux photos superposées",
    pageType: "COLLAGE",
    photoCount: 2,
    pageTitleSlot: null,
    supportedOrientationPatterns: [
      { landscapes: 2, weight: 12 },
      { landscapes: 1, squares: 1, weight: 8 },
    ],
    slots: [
      {
        id: "slot1",
        role: "secondary",
        x: 8,
        y: 6,
        width: 84,
        height: 42,
        rotationDeg: -0.7,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "slot2",
        role: "secondary",
        x: 8,
        y: 52,
        width: 84,
        height: 42,
        rotationDeg: 0.8,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },

  // --- 3 photos ---
  {
    id: "PHOTO_3_A",
    label: "Grande gauche + deux droite",
    pageType: "COLLAGE",
    photoCount: 3,
    pageTitleSlot: { x: 6, y: 2.5, width: 88, height: 5 },
    supportedOrientationPatterns: [
      { landscapes: 1, portraits: 2, weight: 12 },
      { portraits: 2, squares: 1, weight: 9 },
      { portraits: 1, landscapes: 1, squares: 1, weight: 7 },
    ],
    slots: [
      {
        id: "hero",
        role: "hero",
        x: 3,
        y: 9,
        width: 52,
        height: 84,
        rotationDeg: -1.0,
        imageFit: "cover",
        preferredOrientations: ["PORTRAIT", "SQUARE", "LANDSCAPE"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary1",
        role: "secondary",
        x: 58,
        y: 9,
        width: 38,
        height: 40,
        rotationDeg: 1.2,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary2",
        role: "secondary",
        x: 58,
        y: 52,
        width: 38,
        height: 40,
        rotationDeg: -0.9,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },
  {
    id: "PHOTO_3_B",
    label: "Grande haute + deux basses",
    pageType: "COLLAGE",
    photoCount: 3,
    pageTitleSlot: null,
    supportedOrientationPatterns: [
      { landscapes: 3, weight: 14 },
      { landscapes: 2, squares: 1, weight: 11 },
      { landscapes: 2, portraits: 1, weight: 9 },
    ],
    slots: [
      {
        id: "hero",
        role: "hero",
        x: 6,
        y: 5,
        width: 88,
        height: 48,
        rotationDeg: -0.6,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary1",
        role: "secondary",
        x: 5,
        y: 56,
        width: 43,
        height: 38,
        rotationDeg: 1.0,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary2",
        role: "secondary",
        x: 52,
        y: 56,
        width: 43,
        height: 38,
        rotationDeg: -1.1,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },
  {
    id: "PHOTO_3_C",
    label: "Deux gauche + grande droite",
    pageType: "COLLAGE",
    photoCount: 3,
    pageTitleSlot: { x: 6, y: 2.5, width: 88, height: 5 },
    supportedOrientationPatterns: [
      { landscapes: 1, portraits: 2, weight: 11 },
      { portraits: 3, weight: 8 },
      { portraits: 1, landscapes: 2, weight: 6 },
    ],
    slots: [
      {
        id: "secondary1",
        role: "secondary",
        x: 3,
        y: 9,
        width: 38,
        height: 40,
        rotationDeg: -1.0,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary2",
        role: "secondary",
        x: 3,
        y: 52,
        width: 38,
        height: 40,
        rotationDeg: 0.9,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "hero",
        role: "hero",
        x: 44,
        y: 9,
        width: 53,
        height: 84,
        rotationDeg: 1.0,
        imageFit: "cover",
        preferredOrientations: ["PORTRAIT", "SQUARE", "LANDSCAPE"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },

  // --- 4 photos ---
  {
    id: "PHOTO_4_A",
    label: "Grille 2 × 2",
    pageType: "COLLAGE",
    photoCount: 4,
    pageTitleSlot: { x: 10, y: 2, width: 80, height: 5 },
    supportedOrientationPatterns: [
      { landscapes: 4, weight: 8 },
      { portraits: 4, weight: 8 },
      { landscapes: 2, portraits: 2, weight: 10 },
      { squares: 4, weight: 7 },
    ],
    slots: [
      {
        id: "slot1",
        role: "secondary",
        x: 4,
        y: 9,
        width: 44,
        height: 42,
        rotationDeg: -0.8,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "slot2",
        role: "secondary",
        x: 52,
        y: 9,
        width: 44,
        height: 42,
        rotationDeg: 0.9,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "slot3",
        role: "secondary",
        x: 4,
        y: 54,
        width: 44,
        height: 42,
        rotationDeg: 0.7,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "slot4",
        role: "secondary",
        x: 52,
        y: 54,
        width: 44,
        height: 42,
        rotationDeg: -1.0,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },
  {
    id: "PHOTO_4_B",
    label: "Une grande + trois petites",
    pageType: "COLLAGE",
    photoCount: 4,
    pageTitleSlot: null,
    supportedOrientationPatterns: [
      { landscapes: 1, portraits: 3, weight: 11 },
      { landscapes: 1, squares: 3, weight: 9 },
      { landscapes: 2, portraits: 2, weight: 7 },
    ],
    slots: [
      {
        id: "hero",
        role: "hero",
        x: 3,
        y: 5,
        width: 55,
        height: 90,
        rotationDeg: -0.9,
        imageFit: "cover",
        preferredOrientations: ["PORTRAIT", "LANDSCAPE", "SQUARE"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary1",
        role: "secondary",
        x: 61,
        y: 5,
        width: 35,
        height: 28,
        rotationDeg: 1.1,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary2",
        role: "secondary",
        x: 61,
        y: 36,
        width: 35,
        height: 28,
        rotationDeg: -0.8,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
      {
        id: "secondary3",
        role: "secondary",
        x: 61,
        y: 67,
        width: 35,
        height: 28,
        rotationDeg: 0.9,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "POLAROID_BOTTOM",
      },
    ],
  },

  // --- Timeline ---
  {
    id: "PHOTO_TIMELINE_3_A",
    label: "Timeline verticale · 3",
    pageType: "TIMELINE",
    photoCount: 3,
    pageTitleSlot: null,
    supportedOrientationPatterns: [{ weight: 5 }],
    slots: [
      {
        id: "step1",
        role: "timeline",
        x: 28,
        y: 4,
        width: 34,
        height: 28,
        rotationDeg: -0.8,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
      {
        id: "step2",
        role: "timeline",
        x: 28,
        y: 36,
        width: 34,
        height: 28,
        rotationDeg: 0.7,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
      {
        id: "step3",
        role: "timeline",
        x: 28,
        y: 68,
        width: 34,
        height: 28,
        rotationDeg: -0.6,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
    ],
  },
  {
    id: "PHOTO_TIMELINE_4_A",
    label: "Timeline verticale · 4",
    pageType: "TIMELINE",
    photoCount: 4,
    pageTitleSlot: null,
    supportedOrientationPatterns: [{ weight: 5 }],
    slots: [
      {
        id: "step1",
        role: "timeline",
        x: 30,
        y: 2,
        width: 30,
        height: 22,
        rotationDeg: -0.7,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
      {
        id: "step2",
        role: "timeline",
        x: 30,
        y: 26,
        width: 30,
        height: 22,
        rotationDeg: 0.6,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
      {
        id: "step3",
        role: "timeline",
        x: 30,
        y: 50,
        width: 30,
        height: 22,
        rotationDeg: -0.5,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
      {
        id: "step4",
        role: "timeline",
        x: 30,
        y: 74,
        width: 30,
        height: 22,
        rotationDeg: 0.8,
        imageFit: "cover",
        preferredOrientations: ["LANDSCAPE", "SQUARE", "PORTRAIT"],
        captionMode: "SIDE",
      },
    ],
  },
]

export function getPhotoPageTemplate(
  id: string,
): PhotoPageTemplateDefinition | undefined {
  return PHOTO_PAGE_TEMPLATES.find((t) => t.id === id)
}

export function listPhotoTemplatesForCount(
  pageType: "COLLAGE" | "TIMELINE",
  photoCount: number,
): PhotoPageTemplateDefinition[] {
  return PHOTO_PAGE_TEMPLATES.filter(
    (t) => t.pageType === pageType && t.photoCount === photoCount,
  )
}
