import type { PageArchetype } from "./types"

/**
 * Editorial page archetypes — product intent, not generation.
 * READY = producible today; PARTIAL / MISSING = known gaps.
 */
export const PAGE_ARCHETYPES: PageArchetype[] = [
  {
    id: "OPENING_WELCOME",
    family: "OPENING",
    label: "Ouverture",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "PARTIAL",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["opening", "welcome"],
    personalizationType: "NONE",
    dataNeed: "NEUTRAL",
  },
  {
    id: "THEME_QUIZ",
    family: "THEME_GAME",
    label: "Quiz thématique",
    estimatedDensity: "MEDIUM",
    correctionRequired: true,
    correctionWeight: 0.8,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["quiz", "theme", "main"],
    mechanicFamily: "QUIZ",
    gameId: "QUIZ_THEME",
    technicalEngine: "QUIZ",
    personalizationType: "THEME",
    dataNeed: "THEME",
  },
  {
    id: "THEME_WORDSEARCH",
    family: "THEME_GAME",
    label: "Mots mêlés thématiques",
    estimatedDensity: "MEDIUM",
    correctionRequired: true,
    correctionWeight: 0.5,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["wordsearch", "theme", "main"],
    mechanicFamily: "WORDSEARCH",
    gameId: "WORDSEARCH_THEME",
    technicalEngine: "WORDSEARCH",
    personalizationType: "THEME",
    dataNeed: "THEME",
  },
  {
    id: "THEME_CROSSWORD",
    family: "THEME_GAME",
    label: "Mots croisés thématiques",
    estimatedDensity: "HEAVY",
    correctionRequired: true,
    correctionWeight: 0.5,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["crossword", "theme", "main"],
    mechanicFamily: "CROSSWORD",
    gameId: "CROSSWORD_THEME",
    technicalEngine: "CROSSWORD",
    personalizationType: "THEME",
    dataNeed: "THEME",
  },
  {
    id: "THEME_TRUE_FALSE",
    family: "THEME_GAME",
    label: "Vrai ou faux thématique",
    estimatedDensity: "LIGHT",
    correctionRequired: true,
    correctionWeight: 0.4,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["true_false", "theme", "light", "main"],
    mechanicFamily: "TRUE_FALSE",
    gameId: "TRUE_FALSE_THEME",
    technicalEngine: "TRUE_FALSE",
    personalizationType: "THEME",
    dataNeed: "THEME",
  },
  {
    id: "THEME_VARIETY_GAME",
    family: "THEME_GAME",
    label: "Jeu thématique (mécanique à venir)",
    estimatedDensity: "MEDIUM",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["theme", "main", "variety", "gap"],
    mechanicFamily: "VARIETY",
    personalizationType: "THEME",
    dataNeed: "THEME",
  },
  {
    id: "PERSONAL_QUIZ",
    family: "PERSONAL_GAME",
    label: "Quiz personnel",
    estimatedDensity: "MEDIUM",
    correctionRequired: true,
    correctionWeight: 0.8,
    implementationStatus: "READY",
    supportedAudiences: ["DUO", "GROUP"],
    minimumProfileRequirements: { minPersonalFacts: 4 },
    tags: ["quiz", "personal"],
    mechanicFamily: "QUIZ",
    gameId: "QUIZ_PERSONAL",
    technicalEngine: "QUIZ",
    personalizationType: "PERSONAL",
    dataNeed: "DEEP_PERSONAL",
  },
  {
    id: "DUO_INTERACTION",
    family: "PERSONAL_GAME",
    label: "Interaction duo",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["DUO"],
    minimumProfileRequirements: { requiresDuo: true },
    tags: ["duo", "personal", "interaction"],
    personalizationType: "PERSONAL",
    dataNeed: "LIGHT_PERSONAL",
  },
  {
    id: "PERSONAL_REFLECTION",
    family: "PERSONAL_GAME",
    label: "Page personnelle ludique",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["personal", "contemplative", "fun"],
    personalizationType: "PERSONAL",
    dataNeed: "LIGHT_PERSONAL",
  },
  {
    id: "GROUP_WHO_IN_THE_BAND",
    family: "PERSONAL_GAME",
    label: "Qui dans la bande ?",
    estimatedDensity: "MEDIUM",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["GROUP"],
    minimumProfileRequirements: { requiresGroup: true },
    tags: ["group", "personal", "participants"],
    personalizationType: "PERSONAL",
    dataNeed: "LIGHT_PERSONAL",
  },
  {
    id: "MEMORY_TEXT_PAGE",
    family: "MEMORY",
    label: "Bloc souvenir (source jeux — hors Blueprint V1)",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "PARTIAL",
    supportedAudiences: ["*"],
    minimumProfileRequirements: { minMemories: 1 },
    tags: ["memory", "personal", "block", "game-source", "experimental"],
    personalizationType: "PERSONAL",
    dataNeed: "DEEP_PERSONAL",
  },
  {
    id: "PHOTO_MEMORY_PAGE",
    family: "PHOTO",
    label: "Bloc photo legacy (expérimental)",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "PARTIAL",
    supportedAudiences: ["*"],
    minimumProfileRequirements: { minPhotos: 1 },
    tags: ["photo", "memory", "personal", "block", "experimental"],
    personalizationType: "PERSONAL",
    dataNeed: "PHOTO",
  },
  {
    id: "PHOTO_COLLAGE_PAGE",
    family: "PHOTO",
    label: "Album photo / Polaroid",
    estimatedDensity: "MEDIUM",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: { minPhotos: 2 },
    tags: ["photo", "collage", "album", "polaroid"],
    personalizationType: "PERSONAL",
    dataNeed: "PHOTO",
  },
  {
    id: "PHOTO_TIMELINE_PAGE",
    family: "PHOTO",
    label: "Timeline photo",
    estimatedDensity: "MEDIUM",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: { minPhotos: 2 },
    tags: ["photo", "timeline", "album"],
    personalizationType: "PERSONAL",
    dataNeed: "PHOTO",
  },
  {
    id: "PERSONAL_EDITORIAL_PAGE",
    family: "PERSONAL_EDITORIAL",
    label: "Page personnelle composite (expérimental)",
    estimatedDensity: "MEDIUM",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "PARTIAL",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["personal", "editorial", "composite", "experimental", "lab-only"],
    personalizationType: "PERSONAL",
    dataNeed: "LIGHT_PERSONAL",
  },
  {
    id: "PERSONAL_QUICK_GAME",
    family: "QUICK_GAME",
    label: "Jeu rapide personnalisé",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["quick", "personal"],
    personalizationType: "PERSONAL",
    dataNeed: "LIGHT_PERSONAL",
  },
  {
    id: "GROUP_QUICK_GAME",
    family: "QUICK_GAME",
    label: "Jeu rapide de groupe",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["GROUP", "DUO"],
    minimumProfileRequirements: {},
    tags: ["quick", "group"],
    personalizationType: "PERSONAL",
    dataNeed: "LIGHT_PERSONAL",
  },
  {
    id: "LIGHT_ACTIVITY",
    family: "QUICK_GAME",
    label: "Activité légère",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["quick", "light", "activity"],
    personalizationType: "NONE",
    dataNeed: "NEUTRAL",
  },
  {
    id: "BREATHER_PAGE",
    family: "BREATHER",
    label: "Respiration / transition",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "MISSING",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["breather", "transition"],
    personalizationType: "NONE",
    dataNeed: "NEUTRAL",
  },
  {
    id: "COMPACT_CORRECTIONS",
    family: "CORRECTION",
    label: "Réponses & corrections",
    estimatedDensity: "MEDIUM",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "READY",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["correction", "compact"],
    personalizationType: "NONE",
    dataNeed: "NEUTRAL",
  },
  {
    id: "CLOSING_PAGE",
    family: "CLOSING",
    label: "Clôture",
    estimatedDensity: "LIGHT",
    correctionRequired: false,
    correctionWeight: 0,
    implementationStatus: "PARTIAL",
    supportedAudiences: ["*"],
    minimumProfileRequirements: {},
    tags: ["closing"],
    personalizationType: "NONE",
    dataNeed: "NEUTRAL",
  },
]

const byId = new Map(PAGE_ARCHETYPES.map((a) => [a.id, a]))

export function getArchetype(id: string): PageArchetype {
  const a = byId.get(id)
  if (!a) throw new Error(`Unknown page archetype: ${id}`)
  return a
}

export function listArchetypesByFamily(family: PageArchetype["family"]): PageArchetype[] {
  return PAGE_ARCHETYPES.filter((a) => a.family === family)
}

export const READY_THEME_ARCHETYPE_IDS = [
  "THEME_QUIZ",
  "THEME_WORDSEARCH",
  "THEME_CROSSWORD",
  "THEME_TRUE_FALSE",
] as const

export const MAX_CORRECTION_PAGE_DENSITY = 1.6
